version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: banking_postgres
    restart: always
    environment:
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_pass
      POSTGRES_DB: banking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_CONN_INFO=host=postgres port=5432 dbname=banking_db user=banking_user password=banking_pass
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
